module.exports = [
  {
    userID: "user001",
    githubUsername: "johnDoe",
    password: "password123",
    ownedProjects: ["proj001", "proj002"],
    subscribedProjects: ["proj003"],
    firstName: "John",
    lastName: "Doe",
    userImage: "http://example.com/images/john.jpg",
    emailAddress: "john.doe@example.com",
    preferences: {
      difficultyTag: ["easy", "medium"],
      techTags: ["JavaScript", "React", "Node.js"],
      projectTags: ["web development", "backend"],
    },
  },
  {
    userID: "user002",
    githubUsername: "janeSmith",
    password: "password456",
    ownedProjects: ["proj003"],
    subscribedProjects: ["proj001", "proj002"],
    firstName: "Jane",
    lastName: "Smith",
    userImage: "http://example.com/images/jane.jpg",
    emailAddress: "jane.smith@example.com",
    preferences: {
      difficultyTag: ["medium", "hard"],
      techTags: ["Python", "Django"],
      projectTags: ["data science", "machine learning"],
    },
  },
  {
    userID: "user003",
    githubUsername: "aliceJohnson",
    password: "password789",
    ownedProjects: [],
    subscribedProjects: ["proj001", "proj003"],
    firstName: "Alice",
    lastName: "Johnson",
    userImage: "http://example.com/images/alice.jpg",
    emailAddress: "alice.johnson@example.com",
    preferences: {
      difficultyTag: ["easy"],
      techTags: ["HTML", "CSS"],
      projectTags: ["frontend", "design"],
    },
  },
  {
    userID: "NariM11",
    githubUsername: "NariM11",
    ownedProjects: ["100"],
    subscribedProjects: ["100"],
    firstName: "NotNari",
    lastName: "Muldashev",
    userImage: "https://avatars.githubusercontent.com/u/109767334?v=4",
    emailAddress: null,
    preferences: {
      difficultyTags: ["Advanced"],
      techTags: ["Java", "JavaScript"],
      projectTags: ["AI Development", "Machine Learning", "Backend"],
    },
  },
  {
    userID: "nariman-muldashev",
    githubUsername: "nariman-muldashev",
    ownedProjects: [],
    subscribedProjects: [],
    firstName: "",
    lastName: "",
    userImage: "https://avatars.githubusercontent.com/u/155578308?v=4",
    emailAddress: null,
    preferences: { difficultyTags: [], techTags: [], projectTags: [] },
  },
];
